feat/filtering-and-searching
bastionzero/desktop-app pull request #22
Opened 2023-07-17 20:50 UTC by adrianuxinno

Added filtering and searching.

2023-07-18 10:25 UTC, tflpd requested changes

2023-07-18 10:25 UTC, tflpd commented on src-tauri/src/store/filters.rs
I would add a comment here, something like "This creates dynamically the list of available filters based on available data. It parses all different available envirnoments etc from the list of available targets and populate the available filters' values through the available data"
Now if you count the times I used the word available you will realize I probably need some sleep but you can ignore that, you get the point 😅

2023-07-18 10:25 UTC, tflpd commented on src-tauri/src/store/filters.rs
> +    let type_filters = get_filters_from_all_targets(state, |target: &dyn Filterable| target.get_type_filter());
What about status_filters?

2023-07-18 10:25 UTC, tflpd commented on src-tauri/src/store/launch.rs
>    }
Should this get uncommented?

2023-07-18 20:50 UTC, adrianaioanei commented on src-tauri/src/filters/mod.rs
> +            FilterType::Status => true
Fixed, added status filters as well

2023-07-18 20:52 UTC, adrianuxinno commented on src-tauri/src/store/launch.rs
>    }
This is about the launch targets below the targets list. I commented out since we're deferring that feature for now.

2023-07-18 20:52 UTC, adrianuxinno commented
@tflpd this is ready for review again.

2023-07-19 00:07 UTC, tflpd approved these changes

2023-07-19 06:29 UTC, merged